name: propu_engine
description: "Common shared components for PropU frontend interface"
version: 0.0.1
homepage:

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  dartz: ^0.10.1
  dio: ^4.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  freezed: ^2.0.3+1
  freezed_annotation: ^2.0.3
  get_it: ^7.2.0
  injectable: ^1.4.1
  intl: ^0.18.0
  json_annotation: ^4.9.0
  pretty_dio_logger: ^1.2.0-beta
  shared_preferences: ^2.5.3
  tuple: ^2.0.2
  retrofit: ^3.0.1+1
  amplify_auth_cognito: ^2.6.1
  google_sign_in: ^6.3.0
  sign_in_with_apple: ^7.0.1
  flutter_html:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.0.5
  json_serializable: ^6.1.4
  retrofit_generator: ^4.0.1
  injectable_generator: ^1.5.2
  lints: ^5.1.1

flutter:
